### ISSUE TITLE
Spelling correction of the word "definitions" in the home page

### ISSUE THREAD

**Issue by itzrahulyadav** [madebygps/cloud-dictionary-site#1]
There's a typo in the word definitions.

![Screenshot (116)](https://user-images.githubusercontent.com/65400893/218458060-aab8b623-b8f2-46bf-8b5a-83778c6227a6.png)

I would like to work on it.Thanks

**Comment by madebygps** [comment]
thank you :)

**Comment by madebygps** [comment]
merged  PR

**Comment by itzrahulyadav** [comment]
Thanks✌
